"""add_duration_minutes_reminder_fields

Revision ID: fa84cb3985c3
Revises: daa5034677ed
Create Date: 2026-03-17 15:00:05.842704+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa84cb3985c3'
down_revision: Union[str, None] = 'daa5034677ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pn_address_measurements', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    op.add_column('quote_items', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quote_items', 'duration_minutes')
    op.drop_column('pn_address_measurements', 'duration_minutes')
    # ### end Alembic commands ###
